### ISSUE TITLE
DNS not working

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-demo#19]
https://index.torrust-demo.com/

![image](https://github.com/user-attachments/assets/dc87c0c4-1374-406a-b5a9-2cb0132c24eb)

**Comment by josecelano** [comment]
The domain expired on Dec 5th, 2024.

https://www.cdmon.com/en/dominios/whois?dom=torrust-demo.com

![image](https://github.com/user-attachments/assets/ff16c9d1-bb8c-4d49-b97a-7a5a9c868602)

**Comment by cgbosse** [comment]
Renewed.
